import { Estados } from "../types/estado";

export const estados: Estados = {
  Consulta: {
    nombre: "Consulta",
    prioridad: 1,
    accion: "Responder consulta",
    color: "#ff9500",
    etapa: 1,
  },
  Respondido: {
    nombre: "Respondido",
    prioridad: 3,
    accion: "Esperar decisión del cliente",
    color: "#5ac8fa",
    etapa: 2,
  },
  Transito: {
    nombre: "Transito",
    prioridad: 2,
    accion: "Esperar a que llegue",
    color: "#cddc39",
    etapa: 3,
  },
  Recibido: {
    nombre: "Recibido",
    prioridad: 1,
    accion: "Revisar",
    color: "#ffcc00",
    etapa: 4,
  },
  Revisado: {
    nombre: "Revisado",
    prioridad: 1,
    accion: "Presupuestar",
    color: "#ff6b22",
    etapa: 5,
  },
  Presupuestado: {
    nombre: "Presupuestado",
    prioridad: 2,
    accion: "Esperar decisión de cliente",
    color: "#ff2d55",
    etapa: 6,
  },
  Aceptado: {
    nombre: "Aceptado",
    prioridad: 1,
    accion: "Reparar",
    color: "#007aff",
    etapa: 7,
  },
  Abandonado: {
    nombre: "Abandonado",
    prioridad: 5,
    accion: "Evaluar situación",
    color: "#8e8e93",
    etapa: 8,
  },
  Rechazado: {
    nombre: "Rechazado",
    prioridad: 1,
    accion: "Diagnosticar",
    color: "#ff9500",
    etapa: 9,
  },
  Reparado: {
    nombre: "Reparado",
    prioridad: 3,
    accion: "Cobrar reparación",
    color: "#34c759",
    etapa: 10,
  },
  Diagnosticado: {
    nombre: "Diagnosticado",
    prioridad: 3,
    accion: "Cobrar diagnóstico",
    color: "#ff6b35",
    etapa: 11,
  },
  Cobrado: {
    nombre: "Cobrado",
    prioridad: 4,
    accion: "Enviar al cliente",
    color: "#673ab7",
    etapa: 12,
  },
  Enviado: {
    nombre: "Enviado",
    prioridad: 3,
    accion: "Esperar confirmación de entrega",
    color: "#af52de",
    etapa: 13,
  },
  Finalizado: {
    nombre: "Finalizado",
    prioridad: 5,
    accion: "Proceso completado",
    color: "#8e8e93",
    etapa: 14,
  },
  Cancelado: {
    nombre: "Cancelado",
    prioridad: 5,
    accion: "Proceso cancelado",
    color: "#ff3b30",
    etapa: 15,
  },
  
  // ======================================================
  // ESTADOS DE RETROCOMPATIBILIDAD (SISTEMA ANTERIOR)
  // ======================================================
  Indefinido: {
    nombre: "Indefinido",
    prioridad: 5,
    accion: "Revisar y reasignar estado",
    color: "#8e8e93",
    etapa: 0,
  },
  Reparar: {
    nombre: "Reparar",
    prioridad: 1,
    accion: "Migrar a 'Aceptado'",
    color: "#ff3b30",
    etapa: 100, // Etapa alta para indicar que es legacy
  },
  Repuestos: {
    nombre: "Repuestos",
    prioridad: 2,
    accion: "Migrar a 'Aceptado'",
    color: "#009688",
    etapa: 101,
  },
  Entregado: {
    nombre: "Entregado",
    prioridad: 5,
    accion: "Migrar a 'Finalizado'",
    color: "#EEEEEE",
    etapa: 103,
  },
  Venta: {
    nombre: "Venta",
    prioridad: 3,
    accion: "Revisar y reasignar",
    color: "#8e8e93",
    etapa: 104,
  },
  Liquidación: {
    nombre: "Liquidación",
    prioridad: 4,
    accion: "Migrar a 'Cancelado'",
    color: "#8e8e93",
    etapa: 105,
  },
};
