// Este archivo centraliza las acciones
import { 
    login, 
    logout,
    cierraModal,
    abreModal,
    cierraConfirm,
    getReparaciones,
    getReparacion,
    getCliente,
    guardarReparacion,
    eliminarReparacion,
    confirm,
    setCliente,
    setReparacion,
    guardarPresupuesto,
    getProvinciasSelect,
    getUsuariosSelect,
    getLocalidadesPorProvincia,
    getUsuarios,
    guardarUsuario,
    eliminarUsuario,
} from "./App/App.actions";

export { 
    login,
    logout, 
    cierraModal,
    abreModal,
    cierraConfirm,
    getReparaciones,
    getReparacion,
    getCliente,
    guardarReparacion,
    eliminarReparacion,
    confirm,
    setCliente,
    setReparacion,
    guardarPresupuesto,
    getProvinciasSelect,
    getUsuariosSelect,
    getLocalidadesPorProvincia,
    getUsuarios,
    guardarUsuario,
    eliminarUsuario,
}