// Este archivo centraliza las acciones
import { 
    login,
    registro,
    logout,
    cierraModal,
    abreModal,
    cierraConfirm,
    getReparaciones,
    getReparacion,
    getCliente,
    guardarReparacion,
    eliminarReparacion,
    confirm,
    guardarPresupuesto,
    getProvinciasSelect,
    getUsuariosSelect,
    getLocalidadesPorProvincia,
    getUsuarios,
    guardarUsuario,
    eliminarUsuario,
    setUsuario,
    getMessages,
    sendMessage
} from "./App/App.actions";

export { 
    login,
    registro,
    logout, 
    cierraModal,
    abreModal,
    cierraConfirm,
    getReparaciones,
    getReparacion,
    getCliente,
    guardarReparacion,
    eliminarReparacion,
    confirm,
    guardarPresupuesto,
    getProvinciasSelect,
    getUsuariosSelect,
    getLocalidadesPorProvincia,
    getUsuarios,
    guardarUsuario,
    eliminarUsuario,
    setUsuario,
    getMessages,
    sendMessage
}