export const AppTypes = {
    LOGIN: "LOGIN",
    LOGOUT: "LOGOUT",
    CHANGE_EMAIL_LOGIN: "CHANGE_EMAIL_LOGIN",
    CHANGE_PASSWORD_LOGIN: "CHANGE_PASSWORD_LOGIN",
    ISFETCHING_START: "ISFETCHING_START",
    ISFETCHING_COMPLETE: "ISFETCHING_COMPLETE",
    MODAL_ERROR: "MODAL_ERROR",
    GET_REPARACIONES: "GET_REPARACIONES",
    GET_REPARACION: "GET_REPARACION",
    CHANGE_INPUT_REP: "CHANGE_INPUT_REP"
}