export const AppTypes = {
    LOGIN: "LOGIN",
    LOGOUT: "LOGOUT",
    ISFETCHING_START: "ISFETCHING_START",
    ISFETCHING_COMPLETE: "ISFETCHING_COMPLETE",
    MODAL: "MODAL", // Setea el modal
    CONFIRM: "CONFIRM", // Setea el confirm
    GET_REPARACIONES: "GET_REPARACIONES",
    GET_REPARACION: "GET_REPARACION",
    GET_PROVINCIAS_SELECT: "GET_PROVINCIAS_SELECT",
    GET_LOCALIDADES_SELECT: "GET_LOCALIDADES_SELECT",
    GET_USUARIOS: "GET_USUARIOS",
    CLEAR_PRESUPUESTO: "CLEAR_PRESUPUESTO",
    GET_USUARIOS_SELECT: "GET_USUARIOS_SELECT",
    GET_CLIENTE: "GET_CLIENTE",
    SET_USUARIO: "SET_USUARIO"
}