export const AppTypes = {
    LOGIN: "LOGIN",
    LOGOUT: "LOGOUT",
    CHANGE_EMAIL_LOGIN: "CHANGE_EMAIL_LOGIN",
    CHANGE_PASSWORD_LOGIN: "CHANGE_PASSWORD_LOGIN",
    ISFETCHING_START: "ISFETCHING_START",
    ISFETCHING_COMPLETE: "ISFETCHING_COMPLETE",
    MODAL: "MODAL", // Setea el modal
    CONFIRM: "CONFIRM", // Setea el confirm
    GET_REPARACIONES: "GET_REPARACIONES",
    GET_REPARACION: "GET_REPARACION",
    GET_CLIENTE: "GET_CLIENTE",
    CHANGE_INPUT_PRESU: "CHANGE_INPUT_PRESU",
    CHANGE_INPUT_REP: "CHANGE_INPUT_REP",
    CHANGE_INPUT_USU: "CHANGE_INPUT_USU",
    SET_ESTADO: "SET_ESTADO",
    LOAD_USU_TO_PRESU: "LOAD_USU_TO_PRESU",
    GET_PROVINCIAS: "GET_PROVINCIAS",
    GET_LOCALIDADES: "GET_LOCALIDADES",
    SET_LOCALIDAD_PRESU: "SET_LOCALIDAD_PRESU",
    SET_PROVINCIA_PRESU: "SET_PROVINCIA_PRESU",
    SET_LOCALIDAD_CLIENTE: "SET_LOCALIDAD_CLIENTE",
    SET_PROVINCIA_CLIENTE: "SET_PROVINCIA_CLIENTE",
    GET_USUARIOS: "GET_USUARIOS"
}