// supabaseAuthErrors.ts

export const supabaseAuthErrors: Record<string, string> = {
    anonymous_provider_disabled: "Los inicios de sesión anónimos están deshabilitados.",
    bad_code_verifier: "El verificador de código PKCE no coincide con el esperado.",
    bad_json: "El cuerpo de la solicitud no es un JSON válido.",
    bad_jwt: "El JWT proporcionado no es válido.",
    bad_oauth_callback: "Faltan atributos requeridos en la devolución de OAuth.",
    bad_oauth_state: "Estado de OAuth malformado. Verifique su implementación.",
    captcha_failed: "Fallo en la verificación CAPTCHA.",
    conflict: "Conflicto en la base de datos. Verifique condiciones de concurrencia.",
    email_address_invalid: "La dirección de correo electrónico no es válida.",
    email_address_not_authorized: "No autorizado para enviar correos a esta dirección.",
    email_conflict_identity_not_deletable: "Conflicto de identidad al desvincular el correo.",
    email_exists: "La dirección de correo ya está registrada.",
    email_not_confirmed: "Correo electrónico no confirmado.",
    email_provider_disabled: "El registro con correo y contraseña está deshabilitado.",
    flow_state_expired: "El estado del flujo PKCE ha expirado.",
    flow_state_not_found: "El estado del flujo PKCE no se encuentra.",
    hook_payload_invalid_content_type: "El tipo de contenido del hook no es válido.",
    hook_payload_over_size_limit: "La carga útil del hook supera el límite.",
    hook_timeout: "Tiempo de espera del hook alcanzado.",
    hook_timeout_after_retry: "El hook falló tras reintentos.",
    identity_already_exists: "La identidad ya está vinculada a un usuario.",
    identity_not_found: "Identidad no encontrada.",
    insufficient_aal: "Se requiere un nivel de autenticación superior (MFA).",
    invite_not_found: "Invitación no encontrada o expirada.",
    invalid_credentials: "Credenciales inválidas.",
    manual_linking_disabled: "Vinculación manual deshabilitada.",
    mfa_challenge_expired: "El desafío MFA ha expirado.",
    mfa_factor_name_conflict: "Nombre de factor MFA en conflicto.",
    mfa_factor_not_found: "Factor MFA no encontrado.",
    mfa_ip_address_mismatch: "La IP del proceso MFA no coincide.",
    mfa_phone_enroll_not_enabled: "La inscripción de MFA por teléfono está deshabilitada.",
    mfa_phone_verify_not_enabled: "La verificación MFA por teléfono está deshabilitada.",
    mfa_totp_enroll_not_enabled: "La inscripción TOTP está deshabilitada.",
    mfa_totp_verify_not_enabled: "La verificación TOTP está deshabilitada.",
    mfa_verification_failed: "Código MFA incorrecto.",
    mfa_verification_rejected: "Verificación MFA rechazada por política.",
    mfa_verified_factor_exists: "Ya existe un factor MFA verificado.",
    mfa_web_authn_enroll_not_enabled: "Inscripción WebAuthn deshabilitada.",
    mfa_web_authn_verify_not_enabled: "Verificación WebAuthn deshabilitada.",
    no_authorization: "Falta el encabezado de autorización.",
    not_admin: "El usuario no tiene permisos de administrador.",
    oauth_provider_not_supported: "Proveedor OAuth no soportado o deshabilitado.",
    otp_disabled: "El inicio con OTP está deshabilitado.",
    otp_expired: "El código OTP ha expirado.",
    over_email_send_rate_limit: "Demasiados correos enviados a esta dirección.",
    over_request_rate_limit: "Demasiadas solicitudes desde esta IP.",
    over_sms_send_rate_limit: "Demasiados SMS enviados a este número.",
    phone_exists: "El número de teléfono ya está registrado.",
    phone_not_confirmed: "Teléfono no confirmado.",
    phone_provider_disabled: "El registro con teléfono está deshabilitado.",
    provider_disabled: "Proveedor OAuth deshabilitado.",
    provider_email_needs_verification: "El proveedor no verificó el correo electrónico.",
    reauthentication_needed: "Reautenticación requerida para esta acción.",
    reauthentication_not_valid: "Código de reautenticación inválido.",
    refresh_token_not_found: "Token de actualización no encontrado.",
    refresh_token_already_used: "Token de actualización ya fue usado.",
    request_timeout: "Tiempo de espera de la solicitud excedido.",
    same_password: "La nueva contraseña no puede ser igual a la actual.",
    saml_assertion_no_email: "La aserción SAML no contiene correo electrónico.",
    saml_assertion_no_user_id: "La aserción SAML no contiene ID de usuario.",
    saml_entity_id_mismatch: "ID de entidad SAML no coincide.",
    saml_idp_already_exists: "El proveedor SAML ya existe.",
    saml_idp_not_found: "Proveedor de identidad SAML no encontrado.",
    saml_metadata_fetch_failed: "Error al obtener metadatos del proveedor SAML.",
    saml_provider_disabled: "El SSO con SAML está deshabilitado.",
    saml_relay_state_expired: "El estado de retransmisión SAML expiró.",
    saml_relay_state_not_found: "Estado de retransmisión SAML no encontrado.",
    session_expired: "La sesión ha expirado.",
    session_not_found: "Sesión no encontrada.",
    signup_disabled: "Los registros están deshabilitados.",
    single_identity_not_deletable: "No se puede eliminar la única identidad del usuario.",
    sms_send_failed: "Error al enviar el SMS.",
    sso_domain_already_exists: "Dominio SSO ya registrado.",
    sso_provider_not_found: "Proveedor de SSO no encontrado.",
    too_many_enrolled_mfa_factors: "Demasiados factores MFA registrados.",
    unexpected_audience: "Audiencia inesperada en el JWT.",
    unexpected_failure: "Fallo inesperado en el sistema de autenticación.",
    user_already_exists: "El usuario ya existe.",
    user_banned: "El usuario está suspendido temporalmente.",
    user_not_found: "Usuario no encontrado.",
    user_sso_managed: "Este usuario gestionado por SSO no puede ser modificado.",
    validation_failed: "Parámetros inválidos.",
    weak_password: "La contraseña es demasiado débil."
  };
  